name: Model Retraining on Push to Main
on:
  push:
    branches:
      - main
jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Generate and Store Timestamp
      id: timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
        echo "timestamp=$timestamp" >> $GITHUB_ENV
    - name: Check File Permissions
      run: ls -l src/train_model.py
    - name: Set File Permissions
      run: chmod +x src/train_model.py
    - name: Retrain Model
      run: |
        python src/train_model.py --timestamp "$timestamp"
    - name: Evaluate Model and Log Metrics
      run: |
        python src/evaluate_model.py --timestamp "$timestamp"
        metrics_filename="${timestamp}_metrics.json"
        mkdir -p metrics
        mv "$metrics_filename" "metrics/$metrics_filename"
    - name: Store and Version the New Model
      run: |
        model_filename="model_${timestamp}_rf_model.joblib"
        mkdir -p models
        mv "$model_filename" "models/$model_filename"
    - name: Commit and Push Changes
      run: |
        git config --global user.email "vigneshrb250@gmail.com"
        git config --global user.name "vigneshrb250"
        metrics_filename="metrics/${timestamp}_metrics.json"
        model_filename="models/model_${timestamp}_rf_model.joblib"
        git add -f "$metrics_filename" "$model_filename"
        if ! git diff --cached --quiet; then
          git commit -m "Add metrics and updated model for $timestamp"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}